id: QmedCMhTFoAAtV9fKQeEanTLxfU73HawYd9qsMvLEKYtND
description: Returns pong to a ping over http
tags: []
source: .
trigger:
    type: https
    method: GET
    paths:
        - /chat
domains:
    - GeneratedDomain
execution:
    timeout: 10s
    memory: 10MB
    call: ping
